// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5tMQ8gjKX86K8DAaRwReB1AvjxAcwBb8',
    appId: '1:369669263306:web:7b4d6c5b0632956c6b8933',
    messagingSenderId: '369669263306',
    projectId: 'lmsforacademy',
    authDomain: 'lmsforacademy.firebaseapp.com',
    storageBucket: 'lmsforacademy.firebasestorage.app',
    measurementId: 'G-9Y517LBJ15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN4rjYT1ElE54fE804k5fcTZVdxO_BrB0',
    appId: '1:369669263306:android:439a78b2f072da976b8933',
    messagingSenderId: '369669263306',
    projectId: 'lmsforacademy',
    storageBucket: 'lmsforacademy.firebasestorage.app',
  );
}
